[package]
name = "ztcm"
version = "0.1.0"
edition = "2021"
description = "A simple rust clone of Typed Css Modules"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1"
glob = "0.3"